# .air.toml
root = "."
tmp_dir = "tmp"
include_ext = ["go", "tpl", "tmpl", "html"]
exclude_dir = ["assets", "vendor"]
build = {
    bin = "tmp/main" # Path to the binary
    cmd = "go build -o tmp/main" # Command to build the binary
}
watch = {
    delay = 2000 # Delay in milliseconds
}